# Generated by Django 6.0.1 on 2026-01-09 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('balita', 'Balita (0–59 bulan)'), ('anak_sekolah', 'Anak sekolah (5–9 tahun)'), ('remaja', 'Remaja (10–19 tahun)')], max_length=20)),
                ('age_value', models.PositiveIntegerField()),
                ('age_unit', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('measurement_type', models.CharField(choices=[('length', 'Panjang badan (PB, telentang)'), ('height', 'Tinggi badan (TB, berdiri)')], max_length=10)),
                ('user_question', models.TextField()),
                ('vision_findings', models.JSONField(blank=True, null=True)),
                ('rag_citations', models.JSONField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_id', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.CharField(max_length=100)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_photos', to='consultations.consultation')),
            ],
        ),
    ]
